language: python

sudo: false

python:
    - 2.6
    - 2.7

env:
    - DJANGO="django>=1.4,<1.5"
    - DJANGO="django>=1.5,<1.6"
    - DJANGO="django>=1.6,<1.7"
    - DJANGO="django>=1.7,<1.8"

matrix:
    exclude:
        - python: 2.6
          env: DJANGO="django>=1.7,<1.8"

before_install:
    - sh bin/check_signoff.sh

install:
    - pip install -q flake8 coveralls "$DJANGO"

before_script:
    - flake8 modeltree

script:
    - coverage run test_suite.py

after_success:
    - coveralls
